### ISSUE TITLE
本地断网后过N分钟，再连网，zk重连，内存泄漏问题

### ISSUE THREAD

**Issue by wuteng606** [node-modules/zookeeper-cluster-client#13]
data_client文件中 zk 重连函数，for循环，遍历 map的keys，并且会触发 zookeeper-client:watcher事件
![image](https://user-images.githubusercontent.com/19469310/147429360-9ee1e01e-2587-44fd-b897-d42d15828ef7.png)
api_client中监听zookeeper-client:watcher 最终会触发data_client的invokeWithWatcher，因为是操作的同一个map _watchers 会导致一个死循环，map永远无法清空，所以需将data_client中的 for (const key of this._watchers.keys()) 替换为 
const keys = [...this._watchers.keys()];
for(const key of keys)
![image](https://user-images.githubusercontent.com/19469310/147429392-ff1c9d5c-5559-46eb-a6a6-1e86648e8ed9.png)

**Comment by fengmk2** [comment]
closes by https://github.com/node-modules/zookeeper-cluster-client/pull/14
