### ISSUE TITLE
Can you support config multiple zk-servers?

### ISSUE THREAD

**Issue by JimmyDaddy** [node-modules/zookeeper-cluster-client#9]
Like the java version [zkclient](https://github.com/sgroschupf/zkclient/blob/03ccf12c70aca2f771bfcd94d44dc7c4d4a1495e/src/main/java/org/I0Itec/zkclient/ZkClient.java#L89) do.

**Comment by gxcsoccer** [comment]
we do support it, you can config multiple zk-server with comma delimited address

```js
const client = zookeeper.createClient('address_1:2181,address_2:2181');
```
